[window]
padding = { x = 4, y = 4 }

[keyboard]
bindings = [
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
]

[font]
size = 10
normal = { family = "JetBrainsMono Nerd Font" }

[colors.primary]
background = "#$dark_gray1"
foreground = "#$dark_gray11"

[colors.cursor]
text = "#$light_blue12"
cursor = "#$light_blue3"

[colors.selection]
text = "#$dark_blue12"
cursor = "#$dark_blue5"

[colors.normal]
black = "#$dark_gray2"
red = "#$dark_red11"
green = "#$dark_green11"
yellow = "#$dark_yellow11"
blue = "#$dark_blue11"
magenta = "#$dark_plum11"
cyan = "#$dark_cyan11"
white = "#$dark_gray11"

[colors.bright]
black = "#$dark_gray3"
red = "#$dark_red12"
green = "#$dark_green12"
yellow = "#$dark_yellow12"
blue = "#$dark_blue12"
magenta = "#$dark_plum12"
cyan = "#$dark_cyan12"
white = "#$dark_gray12"

[colors.dim]
black = "#$dark_gray1"
red = "#$dark_red10"
green = "#$dark_green10"
yellow = "#$dark_yellow10"
blue = "#$dark_blue10"
magenta = "#$dark_plum10"
cyan = "#$dark_cyan10"
white = "#$dark_gray10"
