icons_format = "<span color='#7c6f64'>{icon}</span>"

[theme]
theme = "native"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "battery"
format = " $icon $percentage "
not_charging_format = " $icon $percentage "
full_format = " $icon $percentage "
missing_format = " $icon none "

[[block]]
block = "sound"
step_width = 1

[[block]]
block = "backlight"
step_width = 1
missing_format = " NA "

[[block]]
block = "keyboard_layout"
driver = "sway"

[[block]]
block = "time"
interval = 5
