eval %sh{kak-lsp}
lsp-enable

hook global WinCreate ^[^*]+$ %{editorconfig-load}

map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'

set-option global tabstop 2
set-option global indentwidth 0

add-highlighter global/ show-whitespaces

define-command find -docstring "find files" -params 1 %{ edit %arg{1} }
complete-command find shell-script-candidates %{ find . -type f }

define-command -docstring 'Invoke fzf to open a file' -params 0 fzf-find-file %{
  evaluate-commands %sh{
    file="$(find . -type f | fzf-tmux -d 15)"
    if [ -n "$file" ]; then
        printf 'edit "%s"\n' "$file"
    fi
  }
}

map global user f ':fzf-find-file<ret>' -docstring 'Find file'

face global value red
face global type yellow
face global variable green
face global module green
face global function cyan
face global string magenta
face global keyword blue
face global operator yellow
face global attribute green
face global comment rgb:6e6e6e
face global documentation comment
face global meta magenta
face global builtin default+b

face global title blue
face global header cyan
face global mono green
face global block magenta
face global link cyan
face global bullet cyan
face global list yellow

face global Default default,default
face global PrimaryCursor rgb:113264,rgb:e6f4fe
face global PrimarySelection rgb:c2e6ff,rgb:004074
face global SecondaryCursor rgb:c2e6ff,rgb:004074
face global SecondarySelection rgb:70b8ff,rgb:0d2847
face global PrimaryCursorEol black,rgb:fffab8
face global SecondaryCursorEol black,rgb:ffe770
face global LineNumbers rgb:6e6e6e,default
face global LineNumberCursor rgb:191919,default+r
face global MenuForeground rgb:eeeeee,rgb:313131
face global MenuBackground rgb:b4b4b4,rgb:222222
face global MenuInfo rgb:6e6e6e
face global Information yellow
face global Error red
face global DiagnosticError red
face global DiagnosticWarning yellow
face global StatusLine rgb:7b7b7b,default
face global StatusLineMode yellow,default
face global StatusLineInfo rgb:7b7b7b,default
face global StatusLineValue green,default
face global StatusCursor rgb:111111,rgb:eeeeee
face global Prompt yellow,default
face global MatchingChar default,default+b
face global Whitespace rgb:2a2a2a,default
face global BufferPadding rgb:2a2a2a,default
