eval %sh{kak-lsp}
lsp-enable

face global value red
face global type yellow
face global variable green
face global module green
face global function cyan
face global string magenta
face global keyword blue
face global operator yellow
face global attribute green
face global comment rgb:$dark_gray9
face global documentation comment
face global meta magenta
face global builtin default+b

face global title blue
face global header cyan
face global mono green
face global block magenta
face global link cyan
face global bullet cyan
face global list yellow

face global Default default,default
face global PrimaryCursor rgb:$light_blue12,rgb:$light_blue3
face global PrimarySelection rgb:$dark_blue12,rgb:$dark_blue5
face global SecondaryCursor rgb:$dark_blue12,rgb:$dark_blue5
face global SecondarySelection rgb:$dark_blue11,rgb:$dark_blue3
face global PrimaryCursorEol black,rgb:$light_yellow3
face global SecondaryCursorEol black,rgb:$light_yellow5
face global LineNumbers rgb:$dark_gray9,default
face global LineNumberCursor rgb:$dark_gray2,default+r
face global MenuForeground rgb:$dark_gray12,rgb:$dark_gray5
face global MenuBackground rgb:$dark_gray11,rgb:$dark_gray3
face global MenuInfo rgb:$dark_gray9
face global Information yellow
face global Error red
face global DiagnosticError red
face global DiagnosticWarning yellow
face global StatusLine rgb:$dark_gray10,default
face global StatusLineMode yellow,default
face global StatusLineInfo rgb:$dark_gray10,default
face global StatusLineValue green,default
face global StatusCursor rgb:$dark_gray1,rgb:$dark_gray12
face global Prompt yellow,default
face global MatchingChar default,default+b
face global Whitespace rgb:$dark_gray4,default+fd
face global BufferPadding rgb:$dark_gray4,default
