call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'sainnhe/gruvbox-material'
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'

call plug#end()

if has('termguicolors')
	set termguicolors
endif

set number
set background=dark

colorscheme gruvbox-material

let mapleader = " "
nnoremap <leader>g :Git<CR>
nnoremap <leader>f :Files<CR>
nnoremap <leader>b :Buffers<CR>
