vim9script

call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'sainnhe/gruvbox-material'
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'yegappan/lsp'

call plug#end()

if has('termguicolors')
  set termguicolors
endif

set number
set background=dark

colorscheme gruvbox-material

var mapleader = " "
nnoremap <leader>g :Git<CR>
nnoremap <leader>f :Files<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap ]d :LspDiagNext<CR>
nnoremap [d :LspDiagPrev<CR>

autocmd User LspSetup call LspOptionsSet({autoHighlightDiags: v:true})

var lspServers = [
  {
    name: 'bashls',
    filetype: ['sh'],
    path: '/usr/bin/bash-language-server',
    args: ['start']
  }
]

autocmd User LspSetup call LspAddServer(lspServers)
